---

customer_name: epheo

rhel7_repos:
  - rhel-7-fast-datapath-rpms
  - rhel-7-server-extras-rpms
  - rhel-7-server-nfv-rpms
  - rhel-7-server-openstack-13-devtools-rpms
  - rhel-7-server-openstack-13-optools-rpms
  - rhel-7-server-openstack-13-rpms
  - rhel-7-server-optional-rpms
  - rhel-7-server-rhceph-3-mon-rpms
  - rhel-7-server-rhceph-3-osd-rpms
  - rhel-7-server-rhceph-3-tools-rpms
  - rhel-7-server-rh-common-rpms
  - rhel-7-server-rpms
  - rhel-ha-for-rhel-7-server-rpms
  - cf-me-5.10-for-rhel-7-rpms 
  - rhel-server-rhscl-7-rpms

rhel8_repos:
  - rhel-8-for-x86_64-baseos-rpms
  - rhel-8-for-x86_64-appstream-rpms
  - rhel-8-for-x86_64-highavailability-rpms
  - ansible-2.8-for-rhel-8-x86_64-rpms
  - satellite-tools-6.5-for-rhel-8-x86_64-rpms
  - openstack-15-for-rhel-8-x86_64-rpms
  - advanced-virt-for-rhel-8-x86_64-rpms
  #- rhceph-4-tools-for-rhel-8-x86_64-rpms