---
  
- name: Install needed packages
  become: yes
  package:
    state: latest
    name: chrony

- name: replace line
  become: yes
  lineinfile: 
    dest: /etc/chrony.conf 
    regexp: 'allow 192.168'
    line: 'allow {{ ctlplane_net.subnet }}'

- name: Enable NTP in firewalld
  become: yes
  ignore_errors: true
  firewalld:
    service: chronyd
    permanent: yes
    state: enabled

- name: enable service npd and ensure it is not masked
  become: yes
  systemd:
    name: chronyd
    enabled: yes
    masked: no

- name: restart service ntp, in all cases, also issue daemon-reload to pick up config changes
  become: yes
  systemd:
    state: restarted
    daemon_reload: yes
    name: chronyd