---

libvirt_guests:

  - name: repository
    root: rhel-7.7.qcow2 
    cloudinit: user-data
    ram: 2048000
    vcpu: 2
    volumes:
      - name: repo-data
        target: vdb
        size: 300
        pool: slow
    ports:
      - name: eth0
        network: internal
        address: 10.42.1.4/24
      - name: eth1
        network: external
        address: 10.42.42.4/24
        gateway: 10.42.42.1
        defroute: true

  - name: ansible
    root: rhel-7.7.qcow2 
    cloudinit: user-data
    ram: 8192000
    vcpu: 4
    ports:
      - name: eth0
        network: external
        address: 10.42.42.5/24
        gateway: 10.42.42.1
        defroute: true

  - name: director
    root: rhel-7.7.qcow2 
    cloudinit: user-data
    ram: 16384000
    vcpu: 6
    ports:
      - name: eth0
        network: internal
        address: 10.42.1.7/24
      - name: eth1
        network: external
        address: 10.42.42.7/24
        gateway: 10.42.42.1
        defroute: true

  - name: director8
    root: rhel-8.0.qcow2 
    cloudinit: user-data
    ram: 16384000
    vcpu: 6
    ports:
      - name: eth0
        network: internal
        address: 10.42.1.8/24
      - name: eth1
        network: external
        address: 10.42.42.8/24
        gateway: 10.42.42.1
        defroute: true