---

guests_rootimg:
  - localpath: downloads/rhel-7.7.qcow2 
    name: rhel-7.7.qcow2 
  - localpath: downloads/rhel-8.0.qcow2
    name: rhel-8.0.qcow2 
  - localpath: downloads/fedora-30.qcow2
    name: fedora-30.qcow2 
guests_rootdisk_pool: fast
guests_rootdisk_pool_path: '/var/lib/libvirt/ssd'
guests_rootdisk_size: 100

libvirt_storage_pools:
  - name: fast
    path: '/var/lib/libvirt/ssd'
  - name: slow
    path: '/mnt/data/vm_storage'

libvirt_networks:
  - name: internal
  - name: external
    gateway: 10.42.42.1
    netmask: 255.255.255.0