---

vbmc_username: root
vbmc_ports:
  - { name: controller-0 , port: 6231 }
  - { name: controller-1 , port: 6232 }
  - { name: controller-2 , port: 6233 }
  - { name: compute-0 , port: 6234 }
  - { name: compute-1 , port: 6235 }
  - { name: ceph-0 , port: 6236 }
  - { name: ceph-1 , port: 6237 }
  - { name: ceph-2 , port: 6238 }

libvirt_guests:

  - name: controller-0
    ram: 20480000
    vcpu: 4
    volumes:
      - name: controller0-root
        target: vda
        size: 100
        pool: fast
      - name: controller0-data
        target: vdb
        size: 100
        pool: slow
    ports:
      - network: internal
      - network: external

  - name: controller-1
    ram: 20480000
    vcpu: 4
    volumes:
      - name: controller1-root
        target: vda
        size: 100
        pool: fast
      - name: controller1-data
        target: vdb
        size: 100
        pool: slow
    ports:
      - network: internal
      - network: external

  - name: controller-2
    ram: 20480000
    vcpu: 4
    volumes:
      - name: controller2-root
        target: vda
        size: 100
        pool: fast
      - name: controller2-data
        target: vdb
        size: 100
        pool: slow
    ports:
      - network: internal
      - network: external

  - name: compute-0
    ram: 20480000
    vcpu: 4
    volumes:
      - name: compute0-root
        target: vda
        size: 100
        pool: fast
      - name: compute0-data
        target: vdb
        size: 100
        pool: slow
    ports:
      - network: internal
      - network: external

  - name: compute-1
    ram: 20480000
    vcpu: 4
    volumes:
      - name: compute1-root
        target: vda
        size: 100
        pool: fast
      - name: compute1-data
        target: vdb
        size: 100
        pool: slow
    ports:
      - network: internal
      - network: external

  - name: ceph-0
    ram: 8192000
    vcpu: 1
    volumes:
      - name: ceph0-root
        target: vda
        size: 100
        pool: fast
      - name: ceph0-journals
        target: vdb
        size: 50
        pool: fast
      - name: ceph0-osd
        target: vdc
        size: 200
        pool: slow
    ports:
      - network: internal

  - name: ceph-1
    ram: 8192000
    vcpu: 1
    volumes:
      - name: ceph1-root
        target: vda
        size: 100
        pool: fast
      - name: ceph1-journals
        target: vdb
        size: 50
        pool: fast
      - name: ceph1-osd
        target: vdc
        size: 200
        pool: slow
    ports:
      - network: internal

  - name: ceph-2
    ram: 8192000
    vcpu: 1
    volumes:
      - name: ceph2-root
        target: vda
        size: 100
        pool: fast
      - name: ceph2-journals
        target: vdb
        size: 50
        pool: fast
      - name: ceph2-osd
        target: vdc
        size: 200
        pool: slow
    ports:
      - network: internal