---


- name: register_group_id
  uri:
    url: "https://localhost/api/v2/groups/{id}/hosts/"
    user: "{{ tower.user }}"
    password: "{{ tower.password }}"
    method: POST
    body_format: json
    body: 
      {
        "id": 1
      }
    validate_certs: False
    force_basic_auth: yes
    status_code: [ 201 ]
  register: group_id

- name: register_host_id
  uri:
    url: "https://localhost/api/v2/groups/{id}/hosts/"
    user: "{{ tower.user }}"
    password: "{{ tower.password }}"
    method: POST
    body_format: json
    body: 
      {
        "id": 1
      }
    validate_certs: False
    force_basic_auth: yes
    status_code: [ 201 ]
  register: host_id

- debug:
    msg: "{{ host_id }}"

- debug:
    msg: "{{ group_id.stdout }}"

- name: associate_host_group
  uri:
    url: "https://localhost/api/v2/groups/{id}/hosts/"
    user: "{{ tower.user }}"
    password: "{{ tower.password }}"
    method: POST
    body_format: json
    body: 
      {
        "id": 1
      }
    validate_certs: False
    force_basic_auth: yes
    status_code: [ 201 ]