---

- hosts: hypervisor
  roles:
    - common
  tasks:
    - block:
      - include_tasks: roles/common/tasks/download.yaml
      rescue:
        - set_fact: 
            message: "Downloads have failed"
          changed_when: True
          notify: telegram
        - fail:
            msg: "{{ message }}"