---

- hosts: 
    - hypervisor
    - undercloud
  roles:
    - common
  gather_facts: no
  tasks:
    - block:
      - include_tasks: roles/common/tasks/download.yaml
        tags: 
          - always
      rescue:
        - set_fact: 
            message: "Downloads have failed"
          changed_when: True
          notify: telegram
        - fail:
            msg: "{{ message }}"