---

- hosts: onboarding
  roles:
    - common
  vars:
    enable_repos:
      - rhel-8-for-x86_64-baseos-rpms
      - rhel-8-for-x86_64-appstream-rpms
      - rhel-8-for-x86_64-highavailability-rpms
      - openstack-16-for-rhel-8-x86_64-rpms
  tasks:
    - include_tasks: roles/common/tasks/predeploy.yaml
    - include_tasks: roles/common/tasks/subscribe_rhsm.yaml