---

- hosts: repository
  roles:
    - common
    - repositories
    - satellite
  vars:
    enable_repos:
      - rhel-7-server-rpms
      - rhel-7-server-rh-common-rpms
      - rhel-7-server-satellite-6.6-rpms
      - rhel-7-server-satellite-maintenance-6-rpms
      - rhel-server-rhscl-7-rpms
      - rhel-7-server-ansible-2.8-rpms
  tasks:
    - block:
        - include_tasks: roles/common/tasks/predeploy.yaml
        - include_tasks: roles/repositories/tasks/create_partition.yaml
        - include_tasks: roles/common/tasks/subscribe_rhsm.yaml
        - include_tasks: roles/satellite/tasks/install.yaml
      rescue:
        - set_fact: 
            message: "I have fail to install the repository server"
          changed_when: True
          notify: telegram
        - fail:
            msg: "{{ message }}"