---

- hosts: idm
  roles:
    - common
  vars:
    enable_repos:
      - rhel-8-for-x86_64-baseos-rpms
      - rhel-8-for-x86_64-appstream-rpms
  tasks:
    - block:
        - include_tasks: roles/common/tasks/predeploy.yaml
        - include_tasks: roles/common/tasks/subscribe_rhsm.yaml
        
- hosts: idm
  roles:
    - ntp