---

- hosts: undercloud
  roles:
    - common
    - director
  vars:
    enable_repos:
      - rhel-9-for-x86_64-baseos-rpms
      - rhel-9-for-x86_64-appstream-rpms
      - rhel-9-for-x86_64-highavailability-rpms
      - openstack-17.1-for-rhel-9-x86_64-rpms
      - fast-datapath-for-rhel-9-x86_64-rpms
  tasks:
    - block:
        - become: yes
          shell: subscription-manager release --set=9.2
        - include_tasks: roles/common/tasks/predeploy.yaml
        - include_tasks: roles/director/tasks/set_hostname.yaml
        - include_tasks: roles/common/tasks/subscribe_rhsm.yaml
        - include_tasks: roles/director/tasks/generate_certs.yaml
          tags: 
            - ssl
            - csr
            - sslimportcert
        - include_tasks: roles/director/tasks/install.yaml
          tags: 
            - install
            - images
            - dns
            - nfv
        - set_fact: 
            message: "OSP Undercloud have been deployed"
          changed_when: True
          notify: telegram
      rescue:
        - set_fact: 
            message: "OSP Undercloud installation have failed"
          changed_when: True
          notify: telegram
        - fail:
            msg: "{{ message }}"
