---

- hosts: undercloud
  roles:
    - common
    - director
  vars:
    enable_repos:
      - rhel-8-for-x86_64-baseos-eus-rpms
      - rhel-8-for-x86_64-appstream-rpms
      - rhel-8-for-x86_64-highavailability-eus-rpms
      - ansible-2.8-for-rhel-8-x86_64-rpms
      - openstack-16-for-rhel-8-x86_64-rpms
      - rhceph-4-tools-for-rhel-8-x86_64-rpms
      - rhel-8-for-x86_64-nfv-rpms
      - advanced-virt-for-rhel-8-x86_64-rpms
      - fast-datapath-for-rhel-8-x86_64-rpms
  tasks:
    - block:
        - become: yes
          shell: subscription-manager release --set=8.1
        - include_tasks: roles/common/tasks/predeploy.yaml
        - include_tasks: roles/director/tasks/set_hostname.yaml
        - include_tasks: roles/common/tasks/subscribe_rhsm.yaml
        - include_tasks: roles/director/tasks/generate_certs.yaml
          tags: ssl
        - include_tasks: roles/director/tasks/install.yaml
        # - include_tasks: roles/director/tasks/conf_docker_proxy.yaml
        - set_fact: 
            message: "OSP Undercloud have been deployed"
          changed_when: True
          notify: telegram
      rescue:
        - set_fact: 
            message: "OSP Undercloud installation have failed"
          changed_when: True
          notify: telegram
        - fail:
            msg: "{{ message }}"
