---

- hosts: hypervisor
  roles:
    - common
    - hypervisor
  tasks:
    - block:
      - include_tasks: roles/hypervisor/tasks/configure_virtual_bmc.yaml
      rescue:
        - set_fact: 
            message: "KVM guests havn't been created"
          changed_when: True
          notify: telegram
        - fail:
            msg: "{{ message }}"