---

- hosts: undercloud
  roles:
    - common
    - director
  gather_facts: no
  tasks:
    - block:
        - include_tasks: roles/director/tasks/instackenv.yaml
        - include_tasks: roles/director/tasks/baremetal_prepare.yaml
      rescue:
        - set_fact: 
            message: "OSP Overcloud provisioning have failed"
          changed_when: True
          notify: telegram
        - fail:
            msg: "{{ message }}"