---

- hosts: undercloud
  roles:
    - common
    - director
  gather_facts: no
  vars_files:
    - roles/hypervisor/vars/openstack.yaml
  vars: 
    enable_fencing: yes
  tasks:
    - block:
        - include_tasks: roles/director/tasks/templates_update.yaml
        - include_tasks: roles/director/tasks/deploy.yaml
        - set_fact: 
            message: "OSP Overcloud have been deployed"
          notify: telegram
      rescue:
        - set_fact: 
            message: "OSP Overercloud installation have failed"
          changed_when: True
          notify: telegram
        - fail:
            msg: "{{ message }}"