---

- hosts: hypervisor
  roles:
    - common
    - hypervisor
  gather_facts: no
  vars_files:
    - roles/openstack/vars/infrastructure_guests.yaml
  tasks:
    - include_tasks: roles/hypervisor/tasks/cleanup.yaml