---

- hosts: hypervisor
  roles:
    - common
    - hypervisor
  tasks:
    - include_tasks: roles/common/tasks/predeploy.yaml
    - include_tasks: roles/common/tasks/update.yaml
    - include_tasks: roles/common/tasks/deploy_userland.yaml
    - include_tasks: roles/hypervisor/tasks/install.yaml
