---

- hosts: hypervisor
  roles:
    - common
    - hypervisor
  vars:
    enable_repos:
      - rhel-7-server-rpms
      - rhel-7-server-extras-rpms
      - rhel-7-server-optional-rpms
  tasks:
    - block:
      - include_tasks: roles/common/tasks/predeploy.yaml
      - include_tasks: roles/common/tasks/manage_repo.yaml
      - include_tasks: roles/common/tasks/update.yaml
      - include_tasks: roles/common/tasks/deploy_userland.yaml
      - include_tasks: roles/hypervisor/tasks/install.yaml
      rescue:
        - set_fact: 
            message: "Got some issues during the hypervisor install..."
          changed_when: True
          notify: telegram
        - fail:
            msg: "{{ message }}"