---

- hosts: idm
  roles:
    - common
    - idm
  vars:
    enable_repos:
      - rhel-8-for-x86_64-baseos-rpms
      - rhel-8-for-x86_64-appstream-rpms
      - rhel-8-for-x86_64-highavailability-rpms
      - ansible-2.8-for-rhel-8-x86_64-rpms
  tasks:
    - block:
      - include_tasks: roles/common/tasks/predeploy.yaml
      - include_tasks: roles/common/tasks/manage_repo.yaml
      - include_tasks: roles/idm/tasks/install.yaml
      rescue:
        - set_fact: 
            message: "IPA installation have failed..."
          changed_when: True
          notify: telegram
        - fail:
            msg: "{{ message }}"