---

- hosts: tower
  roles:
    - common
    - tower
  tasks:
    #- include_tasks: roles/common/tasks/predeploy.yaml
    #- include_tasks: roles/common/tasks/manage_repo.yaml
    - include_tasks: roles/tower/tasks/download.yaml
    #- include_tasks: roles/tower/tasks/install.yaml
    #- include_tasks: roles/tower/tasks/setup_towercli.yaml
    #- include_tasks: roles/tower/tasks/create_project.yaml
    #- include_tasks: roles/tower/tasks/create_inventory.yaml
    #- include_tasks: roles/tower/tasks/create_jobs_templates.yaml