---

- hosts: undercloud
  roles:
    - common
    - director
  tasks:
    #- include_tasks: roles/director/tasks/uninstall.yaml
    - include_tasks: roles/common/tasks/predeploy.yaml
    - include_tasks: roles/common/tasks/manage_repo.yaml
    - include_tasks: roles/director/tasks/generate_certs.yaml
    - include_tasks: roles/director/tasks/install.yaml
    - include_tasks: roles/director/tasks/conf_docker_proxy.yaml
    - include_tasks: roles/director/tasks/docker_images.yaml