---

- hosts: undercloud
  roles:
    - director
  tasks:
    - include_tasks: roles/director/tasks/delete.yaml
    - include_tasks: roles/director/tasks/baremetal_delete.yaml
    - include_tasks: roles/director/tasks/baremetal_prepare.yaml
    - include_tasks: roles/director/tasks/templates_update.yaml
    - include_tasks: roles/director/tasks/deploy.yaml