---

- hosts: repository
  roles:
    - repositories
  tasks:
    - block:
        - include_tasks: roles/repositories/tasks/reposync.yaml
        - set_fact: 
            message: "Local repos are now the latests"
          changed_when: True
          notify: telegram
      rescue:
        - set_fact: 
            message: "Couldn't synchronise the repos.. Is the CDN down ?"
          changed_when: True
          notify: telegram