---

- import_playbook: 01-download_bits.yaml
#- import_playbook: 10-hypervisor_prepare.yaml
- import_playbook: 11-guests_prepare.yaml
- hosts: repository
  gather_facts: no
  tasks:
    - include_tasks: roles/common/tasks/wait_for_host.yaml
- import_playbook: 30-repository_install.yaml
#- import_playbook: repository_synchronise.yaml
- import_playbook: 40-tower_install.yaml
- import_playbook: 41-tower_prepare.yaml
- import_playbook: 60-undercloud_install.yaml
- import_playbook: 61-undercloud_prepare_templates.yaml
- import_playbook: 62-undercloud_prepare_images.yaml
- import_playbook: overcloud_guests_prepare.yaml
- import_playbook: overcloud_prepare.yaml