---

- hosts: tower
  roles:
    - tower
  tasks:
    - include_tasks: roles/tower/tasks/create_project.yaml
    - include_tasks: roles/tower/tasks/create_inventory.yaml
    - include_tasks: roles/tower/tasks/create_jobs_templates.yaml