---

- hosts: tower
  gather_facts: no
  tasks:
    - include_tasks: roles/common/tasks/wait_for_host.yaml
  
- hosts: tower
  roles:
    - common
    - tower
  vars:
    enable_repos:
      - rhel-7-server-rpms
      - rhel-7-server-extras-rpms
      - rhel-7-server-optional-rpms
      - rhel-server-rhscl-7-rpms
      - rhel-7-server-openstack-13-rpms
  tasks:
    - block:
      - include_tasks: roles/common/tasks/predeploy.yaml
      - include_tasks: roles/common/tasks/manage_repo.yaml
      - include_tasks: roles/tower/tasks/install.yaml
      - include_tasks: roles/tower/tasks/setup_license.yaml
      - include_tasks: roles/tower/tasks/setup_towercli.yaml
      rescue:
        - set_fact: 
            message: "Tower installation failed..."
          changed_when: True
          notify: telegram