---

- hosts: undercloud
  gather_facts: no
  tasks:
    - name: Wait for Host to become available...
      local_action: wait_for host={{ ansible_host }} delay=15 port=22 timeout=240 state=started
  
- hosts: undercloud
  roles:
    - common
    - director
  vars:
    enable_repos:
      - rhel-7-server-rpms
      - rhel-7-server-rh-common-rpms
      - rhel-7-server-extras-rpms
      - rhel-7-server-optional-rpms
      - rhel-7-server-openstack-13-rpms
      - rhel-7-server-rhceph-3-mon-rpms
      - rhel-7-server-rhceph-3-osd-rpms
      - rhel-7-server-rhceph-3-tools-rpms
      - rhel-ha-for-rhel-7-server-rpms
  tasks:
    - include_tasks: roles/common/tasks/predeploy.yaml
    - include_tasks: roles/common/tasks/manage_repo.yaml
    - include_tasks: roles/director/tasks/generate_certs.yaml
    - include_tasks: roles/director/tasks/install.yaml
    - include_tasks: roles/director/tasks/conf_docker_proxy.yaml
    - name: Notify Telegram
      delegate_to: localhost
      telegram:
        token: '{{ telegram.token }}'
        chat_id: '{{ telegram.chat_id }}'
        msg: OSP Undercloud is now ready
      when: telegram is defined