---

- name: Cleanup Guests
  ignore_errors: yes
  shell: |
    virsh destroy {{ item.name }}
    virsh undefine {{ item.name }}
  loop: '{{ libvirt.guests }}'

- name: Cleanup root Volumes
  ignore_errors: yes
  shell: |
    {% if item.root is defined %}
    virsh vol-delete --pool {{ guests.rootdisk.pool }} {{ item.name }}-root
    {% else %}
    true
    {% endif %}
  loop: '{{ libvirt.guests }}'

- name: Cleanup Volumes
  ignore_errors: yes
  shell: |
    {% if item.volumes is defined %}
    {% for vol in item.volumes %}
    {% if vol.name != 'repo-data' %}
    virsh vol-delete --pool {{ vol.pool }} {{ vol.name }}
    {% endif %}
    {% endfor %}
    {% else %}
    true
    {% endif %}
  loop: '{{ libvirt.guests }}'

- name: Cleanup Networks
  ignore_errors: yes
  shell: |
    virsh net-destroy {{ item.name }}
    virsh net-undefine {{ item.name }}
  loop: '{{ libvirt.networks }}'