---

- name: Define Storage pools
  shell: |
    if [ -z "$(virsh pool-list --all |grep {{ item.name }})" ]; then
      mkdir -p {{ item.path }}
      echo '{{ lookup("template", "roles/hypervisor/templates/storage_pool.xml.j2") }}' > pool.xml
      virsh pool-define pool.xml
    fi
  loop: '{{ libvirt.storage_pools }}'
  register: command_result
  changed_when: "command_result.stdout != ''"
  when: libvirt.storage_pools is defined

- name: Start Storage pools
  shell: |
    if [ -z "$(virsh pool-list |grep {{ item.name }})" ]; then
      virsh pool-start {{ item.name }}
    fi
  loop: '{{ libvirt.storage_pools }}'
  register: command_result
  changed_when: "command_result.stdout != ''"
  when: libvirt.storage_pools is defined

- name: Copy guest image
  copy: 
    remote_src: True
    src: '{{ item.localpath }}'
    dest: '{{ guests.rootdisk.pool_path }}/{{ item.name }}'
  loop: '{{ guests.rootimgs }}'
  when: libvirt.storage_pools is defined

- name: Refresh Image pool
  shell: |
    virsh pool-refresh --pool {{ guests.rootdisk.pool }}
  when: libvirt.storage_pools is defined

- name: Create Qcow2 Root volumes
  shell: |
    {% if item.root is defined %}
    if [ -z "$(virsh vol-list --pool {{ guests.rootdisk.pool }} |grep \ {{ item.name }}-root )" ]; then
      qemu-img create -f qcow2 -o backing_file={{ guests.rootdisk.pool_path }}/{{ item.root }} {{ guests.rootdisk.pool_path }}/{{ item.name }}-root {{ guests.rootdisk.size }}G
      virsh pool-refresh --pool {{ guests.rootdisk.pool }}
    fi
    {% else %}
    true
    {% endif %}
  loop: '{{ libvirt.guests }}'
  register: command_result
  changed_when: "command_result.stdout != ''"
  tags:
    - guests
  when: item.root is defined

- name: Create Qcow2 volumes
  shell: |
    {% if item.volumes is defined %}
    {% for vol in item.volumes %}
    if [ -z "$(virsh vol-list --pool {{ vol.pool }} |grep \ {{ vol.name }}\  )" ]; then
      virsh vol-create-as --pool {{ vol.pool }} --format qcow2 --name {{ vol.name }} {{ vol.size }}G
    fi
    {% endfor %}
    {% else %}
    true
    {% endif %}
  loop: '{{ libvirt.guests }}'
  register: command_result
  changed_when: "command_result != ''"
  tags:
    - guests
  when: item.volumes is defined