---

- name: Create directory for cloudinit ISOs
  file:
    path: cloudinit/cloudinit_{{ item.name }}
    state: directory
  loop: '{{ libvirt.guests }}'
  tags:
    - guests
    - cloudinit
  when: item.cloudinit is defined

- name: Write Cloud-init meta-data
  template:
    src: ../files/cloudinit/meta-data
    dest: cloudinit/cloudinit_{{ item.name }}/meta-data
  loop: '{{ libvirt.guests }}'
  tags:
    - guests
    - cloudinit
  when: item.cloudinit is defined

- name: Write Cloud-init user-data
  template:
    src: ../files/cloudinit/user-data
    dest: cloudinit/cloudinit_{{ item.name }}/user-data
  loop: '{{ libvirt.guests }}'
  tags:
    - guests
    - cloudinit
  when: item.cloudinit is defined

- name: Write Cloud-init network-config
  template:
    src: ../files/cloudinit/network-config
    dest: cloudinit/cloudinit_{{ item.name }}/network-config
  loop: '{{ libvirt.guests }}'
  tags:
    - guests
    - cloudinit
  when: item.cloudinit is defined

- name: Generate cloudinit ISO
  shell: |
    cd cloudinit/cloudinit_{{ item.name }}/
    genisoimage -output {{ guests.rootdisk.pool_path }}/cloudinit_{{ item.name }}.iso -volid cidata -joliet -rock user-data meta-data network-config
    virsh pool-refresh --pool {{ guests.rootdisk.pool }}
  loop: '{{ libvirt.guests }}'
  tags:
    - guests
    - cloudinit
  when: item.cloudinit is defined

- name: Delete directory
  file:
    path: cloudinit/cloudinit_{{ item.name }}
    state: absent
  loop: '{{ libvirt.guests }}'
  tags:
    - guests
    - cloudinit
  when: item.cloudinit is defined