---

- name: Create directory for cloudinit ISOs
  file:
    path: cloudinit_iso
    state: directory

- name: Create directory for Guests disks
  file:
    path: /mnt/data/vm_storage/
    state: directory

- name: Write CloudInit UserData
  template:
    src: ../files/cloudinit/user-data
    dest: cloudinit_iso/user-data

- name: Write CloudInit Metadata
  template:
    src: ../files/cloudinit/meta-data
    dest: cloudinit_iso/meta-data

- name: Generate cloudinit Metadata ISO
  shell: |
    cd cloudinit_iso/
    genisoimage -output {{ guests_rootdisk_pool_path }}/cloudinit.iso -volid cidata -joliet -rock user-data meta-data
    virsh pool-refresh --pool {{ guests_rootdisk_pool }}