templates: /usr/share/openstack-tripleo-heat-templates/
environments:
  - /usr/share/openstack-tripleo-heat-templates/environments/network-environment.yaml
  - /usr/share/openstack-tripleo-heat-templates/environments/network-isolation.yaml
  - /usr/share/openstack-tripleo-heat-templates/environments/disable-telemetry.yaml
  - /usr/share/openstack-tripleo-heat-templates/environments/host-config-and-reboot.yaml
  - /usr/share/openstack-tripleo-heat-templates/environments/services/neutron-ovs.yaml
  - /usr/share/openstack-tripleo-heat-templates/environments/services/neutron-sriov.yaml
  - /usr/share/openstack-tripleo-heat-templates/environments/services/ironic.yaml # For OVS only
  - /usr/share/openstack-tripleo-heat-templates/environments/services/ironic-inspector.yaml
  - /usr/share/openstack-tripleo-heat-templates/environments/ssl/tls-endpoints-public-dns.yaml
  - /home/stack/containers-prepare-parameter.yaml
  - /home/stack/templates/environments/global.yaml
  - /home/stack/templates/environments/network.yaml
  - /home/stack/templates/environments/sriov.yaml
  - /home/stack/templates/environments/inject-trust-anchor-hiera.yaml
  - /home/stack/templates/environments/enable-tls.yaml
  - /home/stack/templates/environments/ironic.yaml
