# List of networks, used for j2 templating of enabled networks

- name: InternalApi
  name_lower: internal_api
  vip: true
  vlan: '{{ internal_net.vlanid }}'
  ip_subnet: '{{ internal_net.subnet }}'
  allocation_pools: [{'start': '{{ internal_net.pool_start }}', 'end': '{{ internal_net.pool_end }}'}]

- name: Tenant
  name_lower: tenant
  vip: false
  vlan: '{{ tenant_net.vlanid }}'
  ip_subnet: '{{ tenant_net.subnet }}'
  allocation_pools: [{'start': '{{ tenant_net.pool_start }}', 'end': '{{ tenant_net.pool_end }}'}]

- name: External
  name_lower: external
  vip: true
  vlan: '{{ external_net.vlanid }}'
  ip_subnet: '{{ external_net.subnet }}'
  allocation_pools: [{'start': '{{ external_net.pool_start }}', 'end': '{{ external_net.pool_end }}'}]
  gateway_ip: '{{ external_net.gateway }}'

- name: Storage
  name_lower: storage
  vip: true
  vlan: '{{ storage_net.vlanid }}'
  ip_subnet: '{{ storage_net.subnet }}'
  allocation_pools: [{'start': '{{ storage_net.pool_start }}', 'end': '{{ storage_net.pool_end }}'}]

{% if enable_ceph is sameas true %}
- name: StorageMgmt
  name_lower: storage_mgmt
  vip: true
  vlan: '{{ storagemgmt_net.vlanid }}'
  ip_subnet: '{{ storagemgmt_net.subnet }}'
  allocation_pools: [{'start': '{{ storagemgmt_net.pool_start }}', 'end': '{{ storagemgmt_net.pool_end }}'}]
{% endif %}