resource_registry:
  OS::TripleO::NodeUserData: /home/stack/templates/heat/first-boot.yaml

parameter_defaults:

  CloudDomain: {{ customer_name }}.lab 
  CloudName: rhosp.{{ customer_name }}.lab
  CloudNameCtlplane: rhosp.ctlplane.{{ customer_name }}.lab
  CloudNameInternal: rhosp.internalapi.{{ customer_name }}.lab
  CloudNameStorage: rhosp.storage.{{ customer_name }}.lab
  CloudNameStorageManagement: rhosp.storagemgmt.{{ customer_name }}.lab

  ControllerHostnameFormat: 'controller-%index%'
  ControllerCount: 1
  OvercloudControllerFlavor: control

  ComputeHostnameFormat: 'compute-%index%'
  ComputeCount: 3
  OvercloudComputeFlavor: compute

{% if enable_nfvi is sameas true %}
  ComputeOvsDpdkSriovCount: 2
  ComputeOvsDpdkSriovHostnameFormat: 'computeovsdpdksriov-%index%'
  OvercloudComputeOvsDpdkSriovFlavor: computeovsdpdksriov
{% endif %}

{% if enable_ceph is sameas true %}
  CephStorageHostnameFormat: 'ceph-%index%'
  CephStorageCount: 3
  OvercloudCephStorageFlavor: ceph-storage
{% endif %}

{% if enable_ceph is sameas false and enable_ceph_external is sameas false %}
  GlanceBackend: file
{% endif %}