# *******************************************************************
# This file was created automatically by the sample environment
# generator. Developers should use `tox -e genconfig` to update it.
# Users are recommended to make changes to a copy of the file instead
# of the original, if any customizations are needed.
# *******************************************************************
# title: Inject SSL Trust Anchor on Overcloud Nodes
# description: |
#   When using an SSL certificate signed by a CA that is not in the default
#   list of CAs, this environment allows adding a custom CA certificate to
#   the overcloud nodes.
parameter_defaults:
  # Map containing the CA certs and information needed for deploying them.
  # Type: json
  CAMap:
    overcloud-cacert:
      content: |
        -----BEGIN CERTIFICATE-----
        MIIF0TCCA7mgAwIBAgIJAOcgOJI9PpBuMA0GCSqGSIb3DQEBCwUAMH8xCzAJBgNV
        BAYTAlRSMREwDwYDVQQIDAhJc3RhbmJ1bDERMA8GA1UEBwwISXN0YW5idWwxDzAN
        BgNVBAoMBmlzYmFuazEMMAoGA1UECwwDUm5EMQwwCgYDVQQDDANvc3AxHTAbBgkq
        hkiG9w0BCQEWDm9zcEBpc2JhbmsubGFiMB4XDTE5MDkxMzE4MTgyMVoXDTM5MDkw
        ODE4MTgyMVowfzELMAkGA1UEBhMCVFIxETAPBgNVBAgMCElzdGFuYnVsMREwDwYD
        VQQHDAhJc3RhbmJ1bDEPMA0GA1UECgwGaXNiYW5rMQwwCgYDVQQLDANSbkQxDDAK
        BgNVBAMMA29zcDEdMBsGCSqGSIb3DQEJARYOb3NwQGlzYmFuay5sYWIwggIiMA0G
        CSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDsbpv9YWdfRxW6D5SwcWLx/8ZHz+rM
        8WVTjatHNCFrvFp9M6xdJoDqYCr2E9Mh7z0SZPtbFmRkX01uzTa4EVRpK+ejAjO7
        t0O7vCLvk10zNdA4TrCvXP9BlPx5EWsLxgxgrHbb1zF0Bx4171riBLRyA6bTFLu5
        SThOoWbvDXFA61rmYHcVgAwU8EpHNo9h3PVyz7wf9aBvTN+lUnmGT217x/3TUTsJ
        /cuiigylRwx0E0704WeOX9fJZisGbQ2lUVJoe1OzlCoF5asflBmeRojZO6/r68wH
        tr6krUe9I+VR+eWw6iyag1EVkWTyBGSzPPElPZOq/tqHwqTdxoMnzCkJPO6c5g6W
        8/IaefGT5F/wL7SyAunHvoHPdzXqlVVMyFvXkRP1SBuTIzdTNilYqecMh4f69LXC
        c5oRSUSaH6zFveznY6tSBhySc1N4yI/XrY6xq+GI0STIoUSZ+7CtUCwV+P33lZ7A
        vw7cQTXPbtAgftPRYO8BS7GgfU3v47opN3Gv8vW67hcZUljsnRIUCuJkK5hZLYlE
        RDw73T/gG7Dwo1Ue3wAgZLgxZdqaJpUijDPKrPJ5ab6d1Mo8z5vxqx/Q1RPui8Sb
        vkxNpQ1pmoXfadnT7EaxNajiRYkv3CiUQaujzxh6oq4dB+dxMVWT2XZQ3d0cTkrW
        SbN7F9QWQUwx4QIDAQABo1AwTjAdBgNVHQ4EFgQUycbKWm+2VBD0O3vQfVUJSqXk
        TJUwHwYDVR0jBBgwFoAUycbKWm+2VBD0O3vQfVUJSqXkTJUwDAYDVR0TBAUwAwEB
        /zANBgkqhkiG9w0BAQsFAAOCAgEAviJMyUbyTfi3aNWkvDFYhC/gqodY3DiEhimV
        EQPch6jZF8QYt/lEJWlDzKoLcmJslHUDCxi+WwukHG1whBlwO4osgTWDZ1dAgQ1C
        TrFAyvOxa7DZo5G323+vBJZMP1ppNqHN40sLazijJUrXHaL9lxpifYKWYu5rz/Xq
        dkEskB54sAhH0dM7YV74au5120gt9+TxE+YkQQ3X/NjDZPA0tE7p+y7bgz6ACT7F
        khBO/gDgu0KNGxpDoLrRSo7d5fyHAKUr2dBSP3T0f+ivwYaJDH+iIz6UjabEkAW4
        5jafpE1f7/0Qh62IU1KFcykPtQkdQTPclabzoDqMnIOvuNOTBrd/EokG7b4f976V
        Yte46VpapdWxse8FochNgd7n0FX/QnZzRJLL/+++tI2rhNA8qN1PAKuKlmQW5BW2
        dUpPovPNN2ltSl4f9e19zcD9vcLefS/V8CGub1xsLVTQ1s0RKVae0bDU7FI4oE/L
        +1MWspQGl9KfroAoW8nyZUEbLme6RByzaAYYDEuaEV3MBwQiW7Zl8/kHCypPnAEY
        gdijONoRskOYpJ2qmcoJ2b0z6lz41n5aHXaE4U1Hh3mKJw52IBrxqA9LQ85wnLzP
        wEkHuNt+HoTFk/Slw77UchSZAdeeqvoC1vSisUma75HivLYTdkaUmxpyatoirJ1X
        6ddG8co=
        -----END CERTIFICATE-----



# from /etc/pki/ca-trust/source/anchors/cm-local-ca.pem
    undercloud-cacert:
      content: |
        -----BEGIN CERTIFICATE-----
        MIIDjTCCAnWgAwIBAgIQNjzrbj/QRDehuUud8ptLzzANBgkqhkiG9w0BAQsFADBQ
        MSAwHgYDVQQDDBdMb2NhbCBTaWduaW5nIEF1dGhvcml0eTEsMCoGA1UEAwwjMzYz
        Y2ViNmUtM2ZkMDQ0MzctYTFiOTRiOWQtZjI5YjRiY2YwHhcNMTkwOTEyMTc0ODQy
        WhcNMjAwOTEyMTc0ODQyWjBQMSAwHgYDVQQDDBdMb2NhbCBTaWduaW5nIEF1dGhv
        cml0eTEsMCoGA1UEAwwjMzYzY2ViNmUtM2ZkMDQ0MzctYTFiOTRiOWQtZjI5YjRi
        Y2YwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC0n2ux41wKGzrQRhsz
        fn1LnbN3NeBDnIWPPbdee6Ro/Xm6rDkcvr4X6nQHBmbD+g3wZxefWwDLBsxjpkgl
        YTGhYdtKjFeaUN1wKAxMh4UUWtOrx1FZHUigcLmroYoXU2Slh0Y0qGt/UFvnG7Cs
        bYTczEKp62MlvS7XJd+I5+lozcPOFAn63ZpCOU3FaAP7+8JEb8SIRcrEf8qS5tqd
        i7Pjko4f+x8axAGnhT+cNv0htonlxhuoBPz1ViVfIccAi1y59v8Ic1sBB6WNOAUL
        jPBLMvJWakC2jgdnqi/lsvMSk0LjybPjd79Lrn9XyEerRWlQWrvyLIz+vBrX32Jr
        dRBbAgMBAAGjYzBhMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFBaZl+luk55+
        tpTMkNvGCGTE4p4FMB8GA1UdIwQYMBaAFBaZl+luk55+tpTMkNvGCGTE4p4FMA4G
        A1UdDwEB/wQEAwIBhjANBgkqhkiG9w0BAQsFAAOCAQEAaxFuAn7M6gU0M0/pQLS/
        UQdKk99Cco062/XK5sXtROP4qe83q6jU8qhEMG1rVDCRixGKtf3TTTxyELytkmcM
        9BrEQMuw3hVi8YFVpE3Iob1Qu24B/WEHlnaLM1/IEJUXT6NCGtKsg/pfEEe7TreB
        0O7XsW233L+qhZiAC6ZIUAxzsA1VSOiGWoLW4usu+haXWjQ/Gg5KIj0/IYfUyatt
        s7WwJ2e4nyVq5ae+Q8zvwXhPzbgfVlUqGMo0s3if7FNEM1APHXuZRIUgCeNUE/cq
        etFPDKnOKBzbVJBrHZw8GVsASwQz8oYTB7CtBDU5IHHYwPAxdb4TLFhwSz2pdu/x
        Ug==
        -----END CERTIFICATE-----