parameter_defaults:

  OctaviaControlNetwork: 'lb-mgmt-net'
  OctaviaControlSubnet: 'lb-mgmt-subnet'
  OctaviaControlSecurityGroup: 'lb-mgmt-sec-group'
  OctaviaControlSubnetCidr: '172.30.0.0/16'
  OctaviaControlSubnetGateway: '172.30.0.1'
  OctaviaControlSubnetPoolStart: '172.30.0.2'
  OctaviaControlSubnetPoolEnd: '172.30.255.254'

  OctaviaMgmtPortDevName: "o-hm0"

    # This flag enables internal generation of certificates for communication
    # with amphorae. Use OctaviaCaCert, OctaviaCaKey, OctaviaCaKeyPassphrase
    # and OctaviaClient cert to configure secure production environments.
  OctaviaGenerateCerts: true