{% if resource_registry is defined %}
resource_registry:
{% for k, v in resource_registry.items() %}
  {{ k }}: {{ v }}
{% endfor %}
{% endif %}

parameter_defaults:

{% if parameter_defaults is defined %}
{% for k, v in parameter_defaults.items() %}
  {{ k }}: {{ v | to_json }}
{% endfor %}
{% endif %}

  #  Debug: true
  #  ConfigDebug: true
  #  DockerPuppetDebug: True

  # Create user name on install
  #extra_username: redhatstack
  #extra_username_pass: $6$somesaltsalt$kK.nEcss6K201neKzVQFgcGiNg9kIAiWZyhZhKRs9zDAZ.w8aRWfEJpoUE23AdmdEHhE3jcuD7iv82qSEvtQC/

  KeystoneNotificationFormat: cadf

  # CloudForms integration
  CeilometerStoreEvents: true

  NovaSchedulerAvailableFilters: ["nova.scheduler.filters.all_filters","nova.scheduler.filters.pci_passthrough_filter.PciPassthroughFilter"]
  NovaSchedulerDefaultFilters:
    - RetryFilter
    - AggregateInstanceExtraSpecsFilter
    - AvailabilityZoneFilter
    - RamFilter
    - DiskFilter
    - ComputeFilter
    - ComputeCapabilitiesFilter
    - ImagePropertiesFilter
    - ServerGroupAntiAffinityFilter
    - ServerGroupAffinityFilter
    - PciPassthroughFilter
    - NUMATopologyFilter

{% if enable_pcipassthrough is sameas true %}
  NovaPCIPassthrough:
    - vendor_id: "10de"
      product_id: "1eb8"
  
  ControllerExtraConfig:
    nova::api::pci_alias:
      - name: nvidia_t4
        vendor_id: '10de'
        product_id: '1eb8'
{% endif %}

{% if enable_nfvi is sameas true %}
  ComputeParameters:
    NovaReservedHostMemory: 4096

  ComputeExtraConfig:
    nova::cpu_allocation_ratio: 8
    ceilometer::agent::polling::polling_interval: 60

  ComputeNfviExtraConfig:
    nova::cpu_allocation_ratio: 1.9

  ComputeNfviParameters:
    IsolCpusList: 1-23,25-47,49-71,73-95
    KernelArgs: default_hugepagesz=1GB hugepagesz=1G hugepages=180 intel_iommu=on iommu=pt
      isolcpus=1-23,25-47,49-71,73-95
    NovaReservedHostMemory: 4096
    NovaVcpuPinSet: 1-20,22-23,25-40,42-47,49-68,70-71,73-88,90-95
{% if enable_dpdk is sameas true %}
    OvsDpdkCoreList: 0,24,48,72
    OvsDpdkSocketMemory: 3072,1024
    OvsPmdCoreList: 21,41,69,89
{% endif %}
# NUMA node(s):          2
# NUMA node0 CPU(s):     0-23,48-71
# NUMA node1 CPU(s):     24-47,72-95

{% if enable_sriov is sameas true %}
    NeutronPhysicalDevMappings:
      - sriov:p3p1
      - sriov:p3p2

    NeutronSriovNumVFs:
      - p3p1:16
      - p3p2:16
    NovaPCIPassthrough:
      - devname: "p3p1"
        physical_network: "sriov"
      - devname: "p3p2"
        physical_network: "sriov"
{% endif %}
{% endif %}
  
  # Decrease Gnocchi polling time
  ManagePolling: true
  ManagePipeline: true
  PipelinePublishers:
    - gnocchi://?archive_policy=medium
  EventPipelinePublishers:
    - gnocchi://?archive_policy=medium
    - panko://
  GnocchiArchivePolicy: 'medium'

  ExtraConfig:
    heat::engine::heat_waitcondition_server_url: "http://10.245.32.69:8000/v1/waitcondition"
    tripleo::instanceha::no_shared_storage: false
