parameter_defaults:

  CloudDomain: {{ customer_name }}.lab 
  CloudName: rhosp.{{ customer_name }}.lab

  ControllerHostnameFormat: 'controller-%index%'
  ControllerCount: 3
  OvercloudControllerFlavor: control

  ComputeHostnameFormat: 'compute-%index%'
  ComputeCount: 1
  OvercloudComputeFlavor: compute

  ComputeHCIHostnameFormat: 'computehci-%index%'
  ComputeHCICount: 3
  OvercloudComputeHCIFlavor: comphci

  ComputeHCIens1HostnameFormat: 'computehci-%index%'
  ComputeHCIens1Count: 0
  OvercloudCens1omputeHCIFlavor: comphci

  ComputeHCIOvsDpdkHostnameFormat: 'computehcidpdk-%index%'
  ComputeHCIOvsDpdkCount: 0
  OvercloudComputeHCIOvsDpdkFlavor: comphci

  ComputeSriovHostnameFormat: 'computesriov-%index'
  ComputeSriovCount: 0
  OvercloudComputeSriovFlavor: compute

  ComputeOvsDpdkSriovHostnameFormat: 'computeovsdpdksriov-%index%'
  ComputeOvsDpdkSriovCount: 0
  OvercloudComputeOvsDpdkSriovFlavor: compute

  #GlanceBackend: file
