resource_registry:
  OS::TripleO::Controller::Net::SoftwareConfig:  ../nic-config/controller.yaml
  OS::TripleO::ComputeOvsDpdkSriovRT::Net::SoftwareConfig:  ../nic-config/compute.yaml

parameter_defaults:
  DnsServers: [ "{{ dns_ip }}" ]
  NtpServer: "{{ ntp_ip }}"
  TimeZone: 'UTC'
  EC2MetadataIp: "{{ undercloud.ip }}"
  ControlPlaneDefaultRoute: "{{ undercloud.ip }}"
  PublicVirtualFixedIPs: [{ 'ip_address' : "{{ overcloud_vip }}" }]
  
  BondInterfaceOvsOptions: "bond_mode=active-backup"
  BondInterfaceOptions: "mode=active-backup"

  NetworkDeploymentActions: ['CREATE','UPDATE']
  
  NeutronEnableIsolatedMetadata: True
  NeutronEnableForceMetadata: True