resource_registry:
  OS::TripleO::Controller::Net::SoftwareConfig:  ../nic-config/controller.yaml
  OS::TripleO::Compute::Net::SoftwareConfig:  ../nic-config/compute.yaml

parameter_defaults:
  DnsServers: [ "{{ dns_ip }}" ]
  NtpServer: "{{ ntp_ip }}"
  TimeZone: 'UTC'
  EC2MetadataIp: "{{ undercloud.ip }}"
  ControlPlaneDefaultRoute: "{{ undercloud.ip }}"
  PublicVirtualFixedIPs: [{ 'ip_address' : "{{ external_net.vip  }}" }]

  NeutronBridgeMappings: "{{ neutron.bridge_mappings }}"
  NeutronFlatNetworks: "{{ neutron.flat_networks }}"

  NetworkDeploymentActions: ['CREATE','UPDATE']
