
parameter_defaults:

  NeutronNetworkType: 'vxlan,vlan'

  NeutronNetworkVLANRanges:
    - datacentre:1:4094
    - vran-1:1:4094
    - vran-2:1:4094

  NeutronFlatNetworks: datacentre,dpdk

  NeutronOVSFirewallDriver: noop

  ComputeHostnameFormat: 'cpt'


  NeutronMechanismDrivers: ['sriovnicswitch','openvswitch']

  NovaSchedulerDefaultFilters:
    - AvailabilityZoneFilter
    - ComputeFilter
    - ComputeCapabilitiesFilter
    - ImagePropertiesFilter
    - ServerGroupAntiAffinityFilter
    - ServerGroupAffinityFilter
    - PciPassthroughFilter
    - AggregateInstanceExtraSpecsFilter


  ComputeOvsDpdkSriovRTExtraConfig:
    nova::cpu_allocation_ratio: 1.95
  ComputeOvsDpdkSriovRTParameters:
    IsolCpusList: 4-35,40-71 
    KernelArgs: "default_hugepagesz=1GB hugepagesz=1G hugepages=234 intel_iommu=on iommu=pt isolcpus=4-35,40-71"
    NovaReservedHostMemory: 16384
    OvsDpdkCoreList: 0-3,36-39
    OvsDpdkSocketMemory: 4096,4096
    OvsPmdCoreList:  4,5,6,7,40,41,42,43
    NovaComputeCpuDedicatedSet: 8-35,44-71
    NovaComputeCpuSharedSet: 0-3,36-39
    NeutronBridgeMappings:
      - datacentre:br-vnfmgt
      - vran-1:br-vran1
      - vran-2:br-vran2
    NeutronPhysnetNUMANodesMapping: { vran-1: [0], vran-2: [1] }
    NeutronVhostuserSocketDir: "/var/lib/vhost_sockets"
    NeutronDpdkDriverType: vfio-pci
    NeutronDatapathType: netdev
    VhostuserSocketGroup: hugetlbfs 