parameter_defaults:

  NeutronNetworkType: 'vxlan,vlan'

  NeutronNetworkVLANRanges:
    - physnet0:1:4094
    - sriov:1:4094

  NeutronBridgeMappings:
    - physnet0:br-data

  NeutronFlatNetworks: physnet0,dpdk
  NeutronOVSFirewallDriver: noop

  NeutronMechanismDrivers: ['sriovnicswitch','openvswitch']

  NeutronVhostuserSocketDir: "/var/lib/vhost_sockets"
  NeutronDpdkDriverType: vfio-pci
  NeutronDatapathType: netdev

  NovaSchedulerDefaultFilters: 
    - AvailabilityZoneFilter
    - ComputeFilter
    - ComputeCapabilitiesFilter
    - ImagePropertiesFilter
    - ServerGroupAntiAffinityFilter
    - ServerGroupAffinityFilter
    - PciPassthroughFilter
    - AggregateInstanceExtraSpecsFilter

  ComputeHCIExtraConfig:
    nova::cpu_allocation_ratio: 1.95
  ComputeHCIParameters:
    IsolCpusList: 1-19,21-39,41-59,61-79
    KernelArgs: default_hugepagesz=1GB hugepagesz=1G hugepages=190 intel_iommu=on iommu=pt
      isolcpus=1-19,21-39,41-59,61-79
    NovaComputeCpuDedicatedSet: 1-19,21-39,41-59,61-79
    NovaComputeCpuSharedSet: 0,20,40,60
    NovaReservedHostMemory: 86016
    TunedProfileName: "cpu-partitioning"

    NeutronPhysicalDevMappings:
      - sriov:ens4f1
    NeutronSriovNumVFs:
      - ens4f1:64
    NovaPCIPassthrough:
      - devname: ens4f1
        physical_network: "sriov"

  ComputeHCIens1ExtraConfig:
    nova::cpu_allocation_ratio: 1.95
    nova::compute::resume_guests_state_on_host_boot: true
  ComputeHCIens1Parameters:
    IsolCpusList: 1-19,21-39,41-59,61-79
    KernelArgs: default_hugepagesz=1GB hugepagesz=1G hugepages=190 intel_iommu=on iommu=pt
      isolcpus=1-19,21-39,41-59,61-79
    NovaComputeCpuDedicatedSet: 1-19,21-39,41-59,61-79
    NovaComputeCpuSharedSet: 0,20,40,60
    NovaReservedHostMemory: 86016
    TunedProfileName: "cpu-partitioning"
    
    NeutronBridgeMappings:
      - physnet0:br-data
    NeutronPhysicalDevMappings:
      - sriov:ens1f1
    NeutronSriovNumVFs:
      - ens1f1:64
    NovaPCIPassthrough:
      - devname: ens1f1
        physical_network: "sriov"