parameter_defaults:

  NeutronNetworkType: 'vxlan,vlan'
  NeutronNetworkVLANRanges:
    - physnet0:1:4000
  NeutronTunnelTypes: 'vxlan'

  NovaSchedulerDefaultFilters: 
    - AvailabilityZoneFilter
    - ComputeFilter
    - ComputeCapabilitiesFilter
    - ImagePropertiesFilter
    - ServerGroupAntiAffinityFilter
    - ServerGroupAffinityFilter
    - PciPassthroughFilter
    - AggregateInstanceExtraSpecsFilter

  ComputeHCIExtraConfig:                                              
    nova::cpu_allocation_ratio: 1.95                                  
  ComputeHCIParameters:                                               
    IsolCpusList: 1-19,21-39,41-59,61-79                              
    KernelArgs: default_hugepagesz=1GB hugepagesz=1G hugepages=190 intel_iommu=on iommu=pt                                                 
      isolcpus=1-19,21-39,41-59,61-79                                 
    NovaComputeCpuDedicatedSet: 1-19,21-39,41-59,61-79                
    NovaComputeCpuSharedSet: 0,20,40,60                               
    NovaReservedHostMemory: 86016    
    TunedProfileName: "cpu-partitioning"

    NeutronBridgeMappings:
      - physnet0:br-data
    NeutronPhysicalDevMappings:
      - physnet0:ens1f1
      - physnet0:ens4f1
    NeutronSriovNumVFs:
      - ens1f1:8
      - ens4f1:8
    NovaPCIPassthrough:
      - devname: ens1f1
        physical_network: "physnet0"
      - devname: ens4f1
        physical_network: "physnet0"