parameter_defaults:

  NeutronNetworkType: 'vxlan,vlan'

  NeutronNetworkVLANRanges: 
    - datacentre:1:4094
    - vran-1:1:4094
    - vran-2:1:4094'

  NeutronFlatNetworks: physnet0,sriov,dpdk

  NeutronOVSFirewallDriver: noop

  ComputeHostnameFormat: "cpt"

  NeutronMechanismDrivers: ['sriovnicswitch','openvswitch']

  NovaSchedulerDefaultFilters: 
    - AvailabilityZoneFilter
    - ComputeFilter
    - ComputeCapabilitiesFilter
    - ImagePropertiesFilter
    - ServerGroupAntiAffinityFilter
    - ServerGroupAffinityFilter
    - PciPassthroughFilter
    - AggregateInstanceExtraSpecsFilter

  ComputeOvsDpdkSriovRTExtraConfig:
    nova::cpu_allocation_ratio: 1.95
  ComputeOvsDpdkSriovRTParameters:
    IsolCpusList: 2-35,38-71
    KernelArgs: default_hugepagesz=1GB hugepagesz=1G hugepages=126 intel_iommu=on iommu=pt
      isolcpus=2-35,38-71
    NovaComputeCpuDedicatedSet: 2-35,38-71
    NovaComputeCpuSharedSet: 0-1,36-37
    NovaReservedHostMemory: 4096

    NeutronBridgeMappings:
      - datacentre:br-vnfmgt
      - vran-1:br-vran1
      - vran-2:br-vran2
    NeutronPhysnetNUMANodesMapping: { vran-1: [0], vran-2: [1] }
    NeutronVhostuserSocketDir: "/var/lib/vhost_sockets"
    NeutronDpdkDriverType: vfio-pci
    NeutronDatapathType: netdev
    VhostuserSocketGroup: hugetlbfs

    NeutronPhysicalDevMappings:
      - sriov:ens1f1
      - sriov:ens7f1
    NeutronSriovNumVFs:
      - ens1f1:64
      - ens7f1:64
    NovaPCIPassthrough:
      - devname: ens1f1
        physical_network: "sriov"
      - devname: ens7f1
        physical_network: "sriov"
