---

- name: Create job template
  uri:
    url: "https://localhost/api/v2/job_templates/"
    user: "{{ tower.user }}"
    password: "{{ tower.password }}"
    method: POST
    body_format: json
    body: 
      {
        "name": "{{ item.name }}",
        "job_type": "run",
        "inventory": "{{ inventory_id }}",
        "project": "{{ project_id }}",
        "playbook": "{{ item.name }}.yaml",
        "credential": "{{ creds_id }}",
        "extra_vars": "{{ lookup('file', '{{ item.extra_vars }}' ) | from_yaml | to_json }}"
      }
    validate_certs: False
    force_basic_auth: yes
    status_code: [ 201, 400 ]
  register: res
  changed_when: res.status == 201
  loop: "{{ job_templates }}"