---

- name: Create Inventory
  tower_inventory:
    name: "{{ customer_name }}"
    description: "{{ customer_name }} Inventory"
    organization: "{{ customer_name }}"
    state: present
    tower_host: localhost
    tower_username: "{{ tower.user }}"
    tower_password: "{{ tower.password }}"

- name: Create Groups
  tower_group: 
    inventory: "{{ customer_name }}" 
    name: "{{ item }}"
    tower_host: localhost
    tower_username: "{{ tower.user }}"
    tower_password: "{{ tower.password }}"
  loop: 
    - hypervisor
    - extservices
    - undercloud
    - repository
    - tower

- name: Create Hypervisor Host
  tower_host:
    inventory: "{{ customer_name }}" 
    name: "hetznet"
    variables:
      ansible_user: epheo
      ansible_become: True
      ansible_host: ''
    tower_host: localhost
    tower_username: "{{ tower.user }}"
    tower_password: "{{ tower.password }}"

- name: Create Hosts
  tower_host:
    inventory: "{{ customer_name }}" 
    name: "{{ item }}"
    variables:
      ansible_user: stack
      ansible_host: ''
    tower_host: localhost
    tower_username: "{{ tower.user }}"
    tower_password: "{{ tower.password }}"
  loop: 
    - rhservices
    - rhdirector
    - rhrepo
    - rhtower

- name: Associate host group 
  shell: |
    tower-cli login {{ tower.user }} --password {{ tower.password }}
    tower-cli host associate  --host "hetznet" --group "hypervisor"
    tower-cli host associate  --host "rhservices" --group "extservices"
    tower-cli host associate  --host "rhdirector" --group "undercloud"
    tower-cli host associate  --host "rhrepo" --group "repository"
    tower-cli host associate  --host "rhtower" --group "tower"

- name: Add tower credential
  tower_credential:
    name: id_rsa
    description: Team Description
    organization: "{{ customer_name }}"
    kind: ssh
    ssh_key_data: "{{ lookup('file', '~/.ssh/id_rsa') }}"
    state: present
    tower_host: localhost
    tower_username: "{{ tower.user }}"
    tower_password: "{{ tower.password }}"
