---

- name: Create Inventory
  tower_inventory:
    name: "{{ customer_name }}"
    description: "{{ customer_name }} Inventory"
    organization: "{{ customer_name }}"
    state: present
    tower_host: localhost
    tower_username: "{{ tower.user }}"
    tower_password: "{{ tower.password }}"

- name: Create Groups
  tower_group: 
    inventory: "{{ customer_name }}" 
    name: "{{ item }}"
    tower_host: localhost
    tower_username: "{{ tower.user }}"
    tower_password: "{{ tower.password }}"
  loop: 
    - hypervisor
    - extservices
    - undercloud
    - repository
    - tower

- name: Create Hosts
  tower_host:
    inventory: "{{ customer_name }}" 
    name: "{{ item.name }}"
    variables: "{{ item.variables }}"
    tower_host: localhost
    tower_username: "{{ tower.user }}"
    tower_password: "{{ tower.password }}"
  loop: "{{ inventory_hosts }}"

- name: Login to Tower
  shell: |
    tower-cli login {{ tower.user }} --password {{ tower.password }}

- name: Associate host group 
  shell: |
    tower-cli host associate  --host "{{ item.name }}" --group "{{ item.group }}"
  loop: "{{ inventory_hosts }}"
  ignore_errors: True

- name: Add tower credential
  tower_credential:
    name: id_rsa
    description: Team Description
    organization: "{{ customer_name }}"
    kind: ssh
    ssh_key_data: "{{ lookup('file', '~/.ssh/id_rsa') }}"
    state: present
    tower_host: localhost
    tower_username: "{{ tower.user }}"
    tower_password: "{{ tower.password }}"
