---

- name: Unarchive Ansible Tower Installer
  unarchive:
    src: downloads/ansible-tower-setup-bundle-latest.el7.tar.gz
    dest: ~/

- name: Move installer
  shell: mv ansible-tower-setup* tower 
  ignore_errors: true

- name: Set passwords
  lineinfile:
    path: tower/inventory
    regexp: ^admin_password
    line: admin_password='{{ tower.password }}'

- name: Set passwords
  lineinfile:
    path: tower/inventory
    regexp: ^pg_password
    line: pg_password='{{ tower.password }}'

- name: Set passwords
  lineinfile:
    path: tower/inventory
    regexp: ^rabbitmq_password
    line: rabbitmq_password='{{ tower.password }}'

# - name: Install needed packages
#   become: yes
#   package:
#     state: latest
#     name: 'ansible'
    
- name: Run installer
  become: yes
  shell: cd tower && ./setup.sh