---

- name: "Rebooting ..."
  become: yes
  shell: sleep 3 && shutdown -r now
  async: 1
  poll: 0
  listen: "reboot"

- name: Wait for machine to restart. If this is baremetal it can take a while...
  local_action: wait_for host={{ ansible_host }} delay=15 port=22 timeout=240 state=started
  listen: "reboot"

- shell: 'sleep 5'
  delegate_to: localhost
  listen: "reboot"