---

- name: "Rebooting ..."
  become: yes
  shell: sleep 3 && shutdown -r now
  async: 1
  poll: 0
  listen: "reboot"

- shell: 'sleep 10'
  delegate_to: localhost
  listen: "reboot"

- name: Wait for machine to restart. If this is baremetal it can take a while...
  wait_for_connection:
  listen: "reboot"
  
  #local_action: wait_for host={{ ansible_host }} delay=15 port=22 timeout=240 state=started

- shell: 'sleep 5'
  delegate_to: localhost
  listen: "reboot"

- name: telegram
  delegate_to: localhost
  telegram:
    token: '{{ telegram.token }}'
    chat_id: '{{ telegram.chat_id }}'
    msg: "{{ message }}"
  when: telegram is defined

- name: get_rhn_status
  become: yes
  shell: "subscription-manager status |grep 'Overall Status:' |awk '{print $3}'"
  register: rhn_status