---

- name: Create directory templates
  become: yes
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
  when: proxy_url is defined

- name: Write Docker Daemon Proxy file
  become: yes
  template:
    src: ../templates/http-proxy.conf.j2
    dest: /etc/systemd/system/docker.service.d/http-proxy.conf 
  when: proxy_url is defined

- name: restart docker service 
  become: yes
  systemd:
    state: restarted
    daemon_reload: yes
    name: docker
  when: proxy_url is defined