---

- name: Launch Overcloud install
  shell: |
    source ~/stackrc
    time openstack overcloud deploy \
      -n ~/templates/network_data.yaml \
      -r ~/templates/roles_data.yaml \
      --answers-file ~/answers.yaml > overcloud-install.log