---

- name: Install needed packages
  become: yes
  package:
    state: latest
    name: python3-tripleoclient
  tags:
    - install

- name: Install needed packages
  become: yes
  package:
    state: latest
    name: ceph-ansible
  when: enable_ceph is sameas true
  tags:
    - install

- name: Configure Undercloud
  template:
    src: ../templates/undercloud.conf.j2
    dest: ~stack/undercloud.conf
  tags:
    - install

- name: Generate the default container image preparation file
  shell: |
    openstack tripleo container image prepare default \
      --local-push-destination \
      --output-env-file containers-prepare-parameter.yaml
  tags:
    - install

- name: Add username and password to authenticate to that registry
  blockinfile:
    insertafter: EOF
    path: "containers-prepare-parameter.yaml"
    block: |
      #
        ContainerImageRegistryCredentials:
          registry.redhat.io:
            {{ rh_service.username }}: {{ rh_service.token }}
  tags:
    - install


- name: Run undercloud installation
  shell: "openstack undercloud install"
  tags:
    - install

- name: Download overcloud images
  become: yes
  package:
    state: latest
    name:
      - rhosp-director-images-uefi-x86_64
      - rhosp-director-images-ipa-x86_64
  tags:
    - install

- name: Create directory images
  file:
    path: /home/stack/images
    state: directory
    owner: stack
    group: stack
  tags:
    - install

- name: untar images
  shell: "for i in $(ls /usr/share/rhosp-director-images/overcloud-full-latest*) $(ls /usr/share/rhosp-director-images/ironic-python-agent-latest-*); do tar -xvf $i -C /home/stack/images/; done"
  tags:
    - images
  
- name: upload images
  shell: |
    source /home/stack/stackrc && cd ~/images
    for i in /usr/share/rhosp-director-images/ironic-python-agent-latest.tar /usr/share/rhosp-director-images/overcloud-hardened-uefi-full-latest.tar; do tar -xvf $i; done
  tags:
    - images

- name: Set DNS on ctlplane-subnet
  shell: "source /home/stack/stackrc &&  openstack subnet set --dns-nameserver {{ dns_ip }} ctlplane-subnet"
  ignore_errors: yes
  tags:
    - dns

# - name: Create Flavor for Nfvi
#   become: yes
#   shell: |
#     source /home/stack/stackrc
#     openstack flavor create --id auto --ram 4096 --disk 40 --vcpus 1 computenfvi
#     openstack flavor set --property "cpu_arch"="x86_64" --property "capabilities:boot_option"="local" --property "capabilities:profile"="computenfvi" computenfvi
#     openstack flavor set --property resources:VCPU=0 --property resources:MEMORY_MB=0 --property resources:DISK_GB=0 --property resources:CUSTOM_BAREMETAL=1 computenfvi
#   when: enable_nfvi is sameas true
#   tags:
#     - nfv
# 
# - name: Create Flavor for HCI
#   become: yes
#   shell: |
#     source /home/stack/stackrc
#     openstack flavor create --id auto --ram 4096 --disk 40 --vcpus 1 comphci
#     openstack flavor set --property "cpu_arch"="x86_64" --property "capabilities:boot_option"="local" --property "capabilities:profile"="comphci" comphci
#     openstack flavor set --property resources:VCPU=0 --property resources:MEMORY_MB=0 --property resources:DISK_GB=0 --property resources:CUSTOM_BAREMETAL=1 comphci
#   when: enable_hci is sameas true
#   tags:
#     - nfv
