---

- name: Set Timezone
  become: yes
  shell: "timedatectl set-timezone UTC"

- name: Ensure hostname set
  become: yes
  hostname: name={{ inventory_hostname }}
  when: not inventory_hostname is match('(\d{1,3}\.){3}\d{1,3}')

- name: Ensure local hostname is in /etc/hosts
  become: yes
  lineinfile:
    dest: /etc/hosts
    line:  "127.0.0.1\tlocalhost\t{{ ansible_nodename }}\t{{ ansible_hostname }}"
    regexp: '^127\.0\.0\.1\s+'
    insertbefore: BOF

- name: Ensure hostname is in /etc/hosts
  become: yes
  lineinfile:
    dest: /etc/hosts
    line:  "{{ ansible_default_ipv4.address|default(ansible_all_ipv4_addresses[0]) }}\t{{ ansible_nodename }}.{{ customer_name }}.lab\t{{ ansible_hostname }}"
    insertbefore: BOF