---

- name: Register system and add subscription
  become: yes
  redhat_subscription:
    activationkey: '{{ subscription.activation_key }}'
    org_id: '{{ subscription.org }}'
    state: present

- name: Get Pool ID
  become: yes
  shell: |
    subscription-manager list \
     --available --all \
     --matches="Red Hat OpenStack" \
     \ | grep Pool\ ID |awk -F ' ' '{print $3}' |head -n1
  register: pool_id

- debug:
    var: pool_id.stdout_lines[0]
    
- name: Attach Pool ID
  become: yes
  shell: |
    subscription-manager attach --pool={{ pool_id.stdout_lines[0] }}
    
- name: Subscribe repositories
  become: yes
  shell: |
    repo=`cat repo_list`
    subscription-manager repos --disable=*
    subscription-manager repos $(for i in $repo; do echo --enable=$i ;done)

- include_tasks: update.yaml