---

- name: Yum clean all
  become: yes
  shell: |
    yum clean all
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Upgrade all packages
  become: yes
  package:
    name: "*"
    state: latest
  notify: 
    - reboot

- meta: flush_handlers