---

- name: Wait for Host to become available...
  local_action: wait_for host={{ ansible_host }} delay=15 port={{ ansible_port | default(22) }} timeout=240 state=started

- shell: 'sleep 10'
  delegate_to: localhost