---

- name: Install needed packages
  package:
    state: latest
    name: ['ipa-server', 'ipa-server-dns']
    
- name : Set Hostname
  shell: |
    hostnamectl set-hostname rhosp-extservices.{{ customer_name }}.lab
    hostnamectl set-hostname --transient rhosp-extservices.{{ customer_name }}.lab

- name: Ensure hostname is in /etc/hosts
  lineinfile:
    dest: /etc/hosts
    line:  "{{ ansible_host }}\t{{ ansible_nodename }}\t{{ ansible_hostname }}.{{ customer_name }}.lab"
    insertbefore: BOF

- name: Install IPA server
  ignore_errors: yes
  #shell: 'ipa-server-install --realm LABLOCAL --ds-password redhatstack --admin-password redhatstack --unattended --setup-dns  --auto-forwarders --auto-reverse '
  shell: 'ipa-server-install --realm LABLOCAL --ds-password redhatstack --admin-password redhatstack --unattended'

- name: Create base.ldif
  copy:
    dest: "/tmp/base.ldif"
    content: |
      dn: ou=people,dc=lablocal
      objectClass: organizationalUnit
      objectClass: top
      ou: users

      dn: ou=groups,dc=lablocal
      objectClass: organizationalUnit
      objectClass: top
      ou: groups


- name: Create users.ldif
  copy:
    dest: "/tmp/users.ldif"
    content: |
      dn: uid=redhat,ou=people,dc=lablocal
      cn: redhat
      givenName: redhat
      sn: redhat
      uid: redhat
      uidNumber: 1000
      gidNumber: 1000
      homeDirectory: /home/redhat
      mail: redhat@lablocal
      objectClass: top
      objectClass: posixAccount
      objectClass: shadowAccount
      objectClass: inetOrgPerson
      objectClass: inetUser
      loginShell: /bin/bash
      userPassword: redhat

      dn: uid=demo,ou=people,dc=lablocal
      cn: demo
      givenName: demo
      sn: demo
      uid: demo
      uidNumber: 1001
      gidNumber: 1001
      homeDirectory: /home/demo
      mail: demo@lablocal
      objectClass: top
      objectClass: posixAccount
      objectClass: shadowAccount
      objectClass: inetOrgPerson
      objectClass: inetUser
      loginShell: /bin/bash
      userPassword: redhat


      dn: uid=nonosp,ou=people,dc=lablocal
      cn: nonosp
      givenName: nonosp
      sn: nonosp
      uid: nonosp
      uidNumber: 1003
      gidNumber: 1003
      homeDirectory: /home/nonosp
      mail: nonosp@lablocal
      objectClass: top
      objectClass: posixAccount
      objectClass: shadowAccount
      objectClass: inetOrgPerson
      objectClass: inetUser
      loginShell: /bin/bash
      userPassword: redhat



      dn: uid=ceilometer,ou=people,dc=lablocal
      cn: ceilometer
      givenName: ceilometer
      sn: ceilometer
      uid: ceilometer
      uidNumber: 1101
      gidNumber: 1101
      homeDirectory: /home/ceilometer
      mail: ceilometer@lablocal
      objectClass: top
      objectClass: posixAccount
      objectClass: shadowAccount
      objectClass: inetOrgPerson
      objectClass: inetUser
      loginShell: /bin/bash
      userPassword: redhat

      dn: uid=placement,ou=people,dc=lablocal
      cn: placement
      givenName: placement
      sn: placement
      uid: placement
      uidNumber: 1102
      gidNumber: 1102
      homeDirectory: /home/placement
      mail: placement@lablocal
      objectClass: top
      objectClass: posixAccount
      objectClass: shadowAccount
      objectClass: inetOrgPerson
      objectClass: inetUser
      loginShell: /bin/bash
      userPassword: redhat

      dn: uid=ironic,ou=people,dc=lablocal
      cn: ironic
      givenName: ironic
      sn: ironic
      uid: ironic
      uidNumber: 1103
      gidNumber: 1103
      homeDirectory: /home/ironic
      mail: ironic@lablocal
      objectClass: top
      objectClass: posixAccount
      objectClass: shadowAccount
      objectClass: inetOrgPerson
      objectClass: inetUser
      loginShell: /bin/bash
      userPassword: redhat

      dn: uid=aodh,ou=people,dc=lablocal
      cn: aodh
      givenName: aodh
      sn: aodh
      uid: aodh
      uidNumber: 1104
      gidNumber: 1104
      homeDirectory: /home/aodh
      mail: aodh@lablocal
      objectClass: top
      objectClass: posixAccount
      objectClass: shadowAccount
      objectClass: inetOrgPerson
      objectClass: inetUser
      loginShell: /bin/bash
      userPassword: redhat

      dn: uid=octavia,ou=people,dc=lablocal
      cn: octavia
      givenName: octavia
      sn: octavia
      uid: octavia
      uidNumber: 1105
      gidNumber: 1105
      homeDirectory: /home/octavia
      mail: octavia@lablocal
      objectClass: top
      objectClass: posixAccount
      objectClass: shadowAccount
      objectClass: inetOrgPerson
      objectClass: inetUser
      loginShell: /bin/bash
      userPassword: redhat

      dn: uid=sahara,ou=people,dc=lablocal
      cn: sahara
      givenName: sahara
      sn: sahara
      uid: sahara
      uidNumber: 1106
      gidNumber: 1106
      homeDirectory: /home/octavia
      mail: sahara@lablocal
      objectClass: top
      objectClass: posixAccount
      objectClass: shadowAccount
      objectClass: inetOrgPerson
      objectClass: inetUser
      loginShell: /bin/bash
      userPassword: redhat


      dn: uid=neutron,ou=people,dc=lablocal
      cn: neutron
      givenName: neutron
      sn: neutron
      uid: neutron
      uidNumber: 1107
      gidNumber: 1107
      homeDirectory: /home/neutron
      mail: neutron@lablocal
      objectClass: top
      objectClass: posixAccount
      objectClass: shadowAccount
      objectClass: inetOrgPerson
      objectClass: inetUser
      loginShell: /bin/bash
      userPassword: redhat

      dn: uid=heat,ou=people,dc=lablocal
      cn: heat
      givenName: heat
      sn: heat
      uid: heat
      uidNumber: 1108
      gidNumber: 1108
      homeDirectory: /home/heat
      mail: heat@lablocal
      objectClass: top
      objectClass: posixAccount
      objectClass: shadowAccount
      objectClass: inetOrgPerson
      objectClass: inetUser
      loginShell: /bin/bash
      userPassword: redhat

      dn: uid=heat-cfn,ou=people,dc=lablocal
      cn: heat-cfn
      givenName: heat-cfn
      sn: heat-cfn
      uid: heat-cfn
      uidNumber: 1109
      gidNumber: 1109
      homeDirectory: /home/heat-cfn
      mail: heat-cfn@lablocal
      objectClass: top
      objectClass: posixAccount
      objectClass: shadowAccount
      objectClass: inetOrgPerson
      objectClass: inetUser
      loginShell: /bin/bash
      userPassword: redhat

      dn: uid=panko,ou=people,dc=lablocal
      cn: panko
      givenName: panko
      sn: panko
      uid: panko
      uidNumber: 1110
      gidNumber: 1110
      homeDirectory: /home/panko
      mail: panko@lablocal
      objectClass: top
      objectClass: posixAccount
      objectClass: shadowAccount
      objectClass: inetOrgPerson
      objectClass: inetUser
      loginShell: /bin/bash
      userPassword: redhat

      dn: uid=manila,ou=people,dc=lablocal
      cn: manila
      givenName: manila
      sn: manila
      uid: manila
      uidNumber: 1111
      gidNumber: 1111
      homeDirectory: /home/manila
      mail: manila@lablocal
      objectClass: top
      objectClass: posixAccount
      objectClass: shadowAccount
      objectClass: inetOrgPerson
      objectClass: inetUser
      loginShell: /bin/bash
      userPassword: redhat

      dn: uid=nova,ou=people,dc=lablocal
      cn: nova
      givenName: nova
      sn: nova
      uid: nova
      uidNumber: 1112
      gidNumber: 1112
      homeDirectory: /home/nova
      mail: nova@lablocal
      objectClass: top
      objectClass: posixAccount
      objectClass: shadowAccount
      objectClass: inetOrgPerson
      objectClass: inetUser
      loginShell: /bin/bash
      userPassword: redhat

      dn: uid=swift,ou=people,dc=lablocal
      cn: swift
      givenName: swift
      sn: swift
      uid: swift
      uidNumber: 1113
      gidNumber: 1113
      homeDirectory: /home/swift
      mail: swift@lablocal
      objectClass: top
      objectClass: posixAccount
      objectClass: shadowAccount
      objectClass: inetOrgPerson
      objectClass: inetUser
      loginShell: /bin/bash
      userPassword: redhat


      dn: uid=admin,ou=people,dc=lablocal
      cn: admin
      givenName: admin
      sn: admin
      uid: admin
      uidNumber: 1114
      gidNumber: 1114
      homeDirectory: /home/admin
      mail: admin@lablocal
      objectClass: top
      objectClass: posixAccount
      objectClass: shadowAccount
      objectClass: inetOrgPerson
      objectClass: inetUser
      loginShell: /bin/bash
      userPassword: redhat

      dn: uid=manilav2,ou=people,dc=lablocal
      cn: manilav2
      givenName: manilav2
      sn: manilav2
      uid: manilav2
      uidNumber: 1115
      gidNumber: 1115
      homeDirectory: /home/manilav2
      mail: manilav2@lablocal
      objectClass: top
      objectClass: posixAccount
      objectClass: shadowAccount
      objectClass: inetOrgPerson
      objectClass: inetUser
      loginShell: /bin/bash
      userPassword: redhat

      dn: uid=barbican,ou=people,dc=lablocal
      cn: barbican
      givenName: barbican
      sn: barbican
      uid: barbican
      uidNumber: 1116
      gidNumber: 1116
      homeDirectory: /home/barbican
      mail: barbican@lablocal
      objectClass: top
      objectClass: posixAccount
      objectClass: shadowAccount
      objectClass: inetOrgPerson
      objectClass: inetUser
      loginShell: /bin/bash
      userPassword: redhat

      dn: uid=glance,ou=people,dc=lablocal
      cn: glance
      givenName: glance
      sn: glance
      uid: glance
      uidNumber: 1117
      gidNumber: 1117
      homeDirectory: /home/glance
      mail: glance@lablocal
      objectClass: top
      objectClass: posixAccount
      objectClass: shadowAccount
      objectClass: inetOrgPerson
      objectClass: inetUser
      loginShell: /bin/bash
      userPassword: redhat

      dn: uid=gnocchi,ou=people,dc=lablocal
      cn: gnocchi
      givenName: gnocchi
      sn: gnocchi
      uid: gnocchi
      uidNumber: 1118
      gidNumber: 1118
      homeDirectory: /home/gnocchi
      mail: gnocchi@lablocal
      objectClass: top
      objectClass: posixAccount
      objectClass: shadowAccount
      objectClass: inetOrgPerson
      objectClass: inetUser
      loginShell: /bin/bash
      userPassword: redhat

      dn: uid=cinder,ou=people,dc=lablocal
      cn: cinder
      givenName: cinder
      sn: cinder
      uid: cinder
      uidNumber: 1119
      gidNumber: 1119
      homeDirectory: /home/cinder
      mail: cinder@lablocal
      objectClass: top
      objectClass: posixAccount
      objectClass: shadowAccount
      objectClass: inetOrgPerson
      objectClass: inetUser
      loginShell: /bin/bash
      userPassword: redhat


- name: Create groups.ldif
  copy:
    dest: "/tmp/groups.ldif"
    content: |
      dn: cn=openstack-users,ou=groups,dc=lablocal
      objectClass: groupofnames
      cn: openstack-users
      description: All users
      member: uid=redhat,ou=people,dc=lablocal
      member: uid=demo,ou=people,dc=lablocal

      dn: cn=openstack-service,ou=groups,dc=lablocal
      objectClass: groupofnames
      cn: openstack-service
      description: All users
      member: uid=ceilometer,ou=people,dc=lablocal
      member: uid=placement,ou=people,dc=lablocal
      member: uid=ironic,ou=people,dc=lablocal
      member: uid=aodh,ou=people,dc=lablocal
      member: uid=octavia,ou=people,dc=lablocal
      member: uid=sahara,ou=people,dc=lablocal
      member: uid=neutron,ou=people,dc=lablocal
      member: uid=heat,ou=people,dc=lablocal
      member: uid=heat-cfn,ou=people,dc=lablocal
      member: uid=panko,ou=people,dc=lablocal
      member: uid=manila,ou=people,dc=lablocal
      member: uid=redhat,ou=people,dc=lablocal
      member: uid=nova,ou=people,dc=lablocal
      member: uid=swift,ou=people,dc=lablocal
      member: uid=admin,ou=people,dc=lablocal
      member: uid=manilav2,ou=people,dc=lablocal
      member: uid=barbican,ou=people,dc=lablocal
      member: uid=glance,ou=people,dc=lablocal
      member: uid=gnocchi,ou=people,dc=lablocal
      member: uid=cinder,ou=people,dc=lablocal


      dn: cn=othernonosp,ou=groups,dc=lablocal
      objectClass: groupofnames
      cn: othernonosp
      description: All users
      member: uid=nonosp,ou=people,dc=lablocal


- name: Configure base infrastructure
  ignore_errors: yes
  shell: |
    ldapadd -x -D cn="Directory Manager" -w redhatstack -f /tmp/base.ldif

- name: Create user and groups
  ignore_errors: yes
  shell: |
    ldapadd -x -D cn="Directory Manager" -f /tmp/users.ldif -w redhatstack
    ldapadd -x -D cn="Directory Manager" -f /tmp/groups.ldif -w redhatstack


- name: Restart the IPA Server
  shell: 'ipactl restart'
