---

tower_url: '10.42.1.16'
#tower_url: "{{ hostvars.rhtower.ansible_host }}"

job_templates:
  - name: prepare_hypervisor
    extra_vars: 'secrets/kvm.yaml'
  - name: prepare_hypervisor_guests
    extra_vars: 'secrets/kvm.yaml'
  - name: delete_hypervisor_guests
    extra_vars: 'secrets/kvm.yaml'
  - name: prepare_repository
    extra_vars: 'secrets/rhn.yaml'
  - name: prepare_tower
    extra_vars: 'secrets/tower.yaml'
  - name: prepare_undercloud
    extra_vars: 'secrets/director.yaml'
  - name: delete_undercloud
    extra_vars: 'secrets/director.yaml'
  - name: prepare_overcloud
    extra_vars: 'secrets/director.yaml'
  - name: delete_overcloud
    extra_vars: 'secrets/director.yaml'